doc:
	pandoc ./Overview.md -c ./chubby_bunny.css -o ./Overview.html
	pandoc ./Client.md -c ./chubby_bunny.css -o ./Client.html
	pandoc ./ClientMain.md -c ./chubby_bunny.css -o ./ClientMain.html
	pandoc ./ClientPacketHandler.md -c ./chubby_bunny.css -o ./ClientPacketHandler.html
	pandoc ./ClientWorld.md -c ./chubby_bunny.css -o ./ClientWorld.html
	pandoc ./Graphics.md -c ./chubby_bunny.css -o ./Graphics.html
	pandoc ./GUI.md -c ./chubby_bunny.css -o ./GUI.html
	pandoc ./level.md -c ./chubby_bunny.css -o ./level.html
	pandoc ./Packet.md -c ./chubby_bunny.css -o ./Packet.html
	pandoc ./Server.md -c ./chubby_bunny.css -o ./Server.html
	pandoc ./ServerMain.md -c ./chubby_bunny.css -o ./ServerMain.html
	pandoc ./ServerPacketHandler.md -c ./chubby_bunny.css -o ./ServerPacketHandler.html
	pandoc ./Stroke.md -c ./chubby_bunny.css -o ./Stroke.html
	pandoc ./World.md -c ./chubby_bunny.css -o ./World.html
	pandoc ./WorldPhysics.md -c ./chubby_bunny.css -o ./WorldPhysics.html
	pandoc ./Game.md -c ./chubby_bunny.css -o ./Game.html